parameters:
  SOURCE_REPO: $(Build.Repository.Uri)
  SOURCE_BRANCH: $(Build.SourceBranchName)
  TARGET_ENDPOINTS: ''

jobs:
  - job: MirrorRepo
    variables:
      skipComponentGovernanceDetection: true
    steps:
    - template: step-mirror.yml
      parameters:
        SOURCE_REPO: ${{ parameters.SOURCE_REPO }}
        SOURCE_BRANCHES: ${{ parameters.SOURCE_BRANCH }}
        TARGET_ENDPOINTS: ${{ parameters.TARGET_ENDPOINTS }}
