trigger:
  batch: true
  branches:
    include:
      - master
pr: none

# Triggered every 15 minutes
# Azure Pipeline has limitation that every cron entry chould be trigged 100 times per week
# so we have one cron for every day since 60/15*24=96
schedules:
  - cron: "*/15 * * * 0"
    branches:
      include:
      - master
    always: true
  - cron: "*/15 * * * 1"
    branches:
      include:
      - master
    always: true
  - cron: "*/15 * * * 2"
    branches:
      include:
      - master
    always: true
  - cron: "*/15 * * * 3"
    branches:
      include:
      - master
    always: true
  - cron: "*/15 * * * 4"
    branches:
      include:
      - master
    always: true
  - cron: "*/15 * * * 5"
    branches:
      include:
      - master
    always: true
  - cron: "*/15 * * * 6"
    branches:
      include:
      - master
    always: true

jobs:
  - job: MirrorRepos
    variables:
      skipComponentGovernanceDetection: true

    steps:
      - checkout: self
        clean: true
        fetchDepth: 2
        persistCredentials: true

      # Cache repo on daily basis to speed up clone
      - script: echo "##vso[task.setvariable variable=DATE_STRING]$(date +%y%m%d)"
        displayName: Set Date Variable

      - task: CacheBeta@0
        inputs:
          key: cache-repos | "$(DATE_STRING)" | "$(WORKING_DIRECTORY)"
          path: repos
        displayName: Cache Cloned Repos

      - template: step-mirror.yml
        parameters:
          WORKING_DIRECTORY: $(WORKING_DIRECTORY)
          SOURCE_REPO: $(SOURCE_REPO)
          SOURCE_BRANCHES: $(SOURCE_BRANCHES)
          TARGET_ENDPOINTS: $(TARGET_ENDPOINTS)

    strategy:
      matrix:

        # test_sync:
        #   WORKING_DIRECTORY: repos/test-sync
        #   SOURCE_REPO: https://github.com/test-repo-billy/test-sync.git
        #   SOURCE_BRANCHES: master
        #   TARGET_ENDPOINTS: |
        #     https://github.com/test-repo-tih/test-sync.git!master
        #     https://github.com/test-repo-tih/test-sync.git!latest

        azure_rest_api_specs:
          WORKING_DIRECTORY: repos/azure-rest-api-specs
          SOURCE_REPO: https://github.com/Azure/azure-rest-api-specs
          SOURCE_BRANCHES: master
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-rest-api-specs-pr!master
            https://github.com/test-repo-billy/azure-rest-api-specs-pr!master
            https://github.com/test-repo-billy/azure-rest-api-specs!master

        azure_sdk_for_go:
          WORKING_DIRECTORY: repos/azure-sdk-for-go
          SOURCE_REPO: https://github.com/Azure/azure-sdk-for-go
          SOURCE_BRANCHES: master latest
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-sdk-for-go-pr!master
            https://github.com/test-repo-tih/azure-sdk-for-go!master
            https://github.com/test-repo-billy/azure-sdk-for-go!master
            https://github.com/AzureSDKAutomation/azure-sdk-for-go!master
            https://github.com/Azure/azure-sdk-for-go-pr!latest
            https://github.com/test-repo-tih/azure-sdk-for-go!latest
            https://github.com/test-repo-billy/azure-sdk-for-go!latest
            https://github.com/AzureSDKAutomation/azure-sdk-for-go!latest

        azure_sdk_for_js:
          WORKING_DIRECTORY: repos/azure-sdk-for-js
          SOURCE_REPO: https://github.com/azure/azure-sdk-for-js
          SOURCE_BRANCHES: master
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-sdk-for-js-pr!master
            https://github.com/test-repo-tih/azure-sdk-for-js!master
            https://github.com/test-repo-billy/azure-sdk-for-js!master
            https://github.com/azuresdkautomation/azure-sdk-for-js!master

        azure_sdk_for_net:
          WORKING_DIRECTORY: repos/azure-sdk-for-net
          SOURCE_REPO: https://github.com/azure/azure-sdk-for-net
          SOURCE_BRANCHES: master
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-sdk-for-net-pr!master
            https://github.com/test-repo-tih/azure-sdk-for-net!master
            https://github.com/test-repo-billy/azure-sdk-for-net!master
            https://github.com/azuresdkautomation/azure-sdk-for-net!master

        azure_sdk_for_python:
          WORKING_DIRECTORY: repos/azure-sdk-for-python
          SOURCE_REPO: https://github.com/azure/azure-sdk-for-python
          SOURCE_BRANCHES: master
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-sdk-for-python-pr!master
            https://github.com/test-repo-tih/azure-sdk-for-python!master
            https://github.com/test-repo-billy/azure-sdk-for-python!master
            https://github.com/azuresdkautomation/azure-sdk-for-python!master

        azure_sdk_for_java:
          WORKING_DIRECTORY: repos/azure-sdk-for-java
          SOURCE_REPO: https://github.com/azure/azure-sdk-for-java
          SOURCE_BRANCHES: master
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-sdk-for-java-pr!master
            https://github.com/test-repo-tih/azure-sdk-for-java!master
            https://github.com/test-repo-billy/azure-sdk-for-java!master
            https://github.com/azuresdkautomation/azure-sdk-for-java!master

        # azure_sdk_for_ruby:
        #   WORKING_DIRECTORY: repos/azure-sdk-for-ruby
        #   SOURCE_REPO: https://github.com/azure/azure-sdk-for-ruby
        #   SOURCE_BRANCHES: master latest
        #   TARGET_ENDPOINTS: |
        #     https://github.com/Azure/azure-sdk-for-ruby-pr!master
        #     https://github.com/test-repo-tih/azure-sdk-for-ruby!master
        #     https://github.com/test-repo-billy/azure-sdk-for-ruby!master
        #     https://github.com/azuresdkautomation/azure-sdk-for-ruby!master
        #     https://github.com/Azure/azure-sdk-for-ruby-pr!latest
        #     https://github.com/test-repo-tih/azure-sdk-for-ruby!latest
        #     https://github.com/test-repo-billy/azure-sdk-for-ruby!latest
        #     https://github.com/azuresdkautomation/azure-sdk-for-ruby!latest

        azure_cli:
          WORKING_DIRECTORY: repos/azure-cli
          SOURCE_REPO: https://github.com/azure/azure-cli
          SOURCE_BRANCHES: dev
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-cli-pr!dev

        azure_cli_extensions:
          WORKING_DIRECTORY: repos/azure-cli-extensions
          SOURCE_REPO: https://github.com/azure/azure-cli-extensions
          SOURCE_BRANCHES: master
          TARGET_ENDPOINTS: |
            https://github.com/Azure/azure-cli-extensions-pr!master
            https://github.com/test-repo-tih/azure-cli-extensions!master
