parameters:
  SOURCE_REPO: $(Build.Repository.Uri)
  SOURCE_BRANCHES: $(Build.SourceBranchName)
  TARGET_ENDPOINTS: ''
  WORKING_DIRECTORY: ''

steps:
- script: mkdir -p ${{ parameters.WORKING_DIRECTORY }}
  displayName: mkdir -p ${{ parameters.WORKING_DIRECTORY }}
  condition: ne('${{ parameters.WORKING_DIRECTORY }}', '')
- script: |
    EXIT_CODE=0
    trap "EXIT_CODE=-1" ERR

    git --version
    [ -z $(github-pat) ] && echo "github-pat is empty" && exit -1
    echo

    set -x

    SOURCE_REPO=${{ parameters.SOURCE_REPO }}
    SOURCE_BRANCHES='${{ parameters.SOURCE_BRANCHES }}'
    TARGET_ENDPOINTS='${{ parameters.TARGET_ENDPOINTS }}'
    git init
    git config user.email "azuresdkci@microsoft.com"
    git config user.name "azuresdkci"
    git config credential.helper store
    echo https://$(github-pat):x-oauth-basic@github.com > ~/.git-credentials
    git reset --hard HEAD 2> /dev/null || truee
    git remote remove source 2> /dev/null || true
    git remote add source $SOURCE_REPO
    git fetch --no-tags source $SOURCE_BRANCH

    for SOURCE_BRANCH in $SOURCE_BRANCHES
    do
      set -x
      git checkout --detach source_branch 2> /dev/null && git branch -D source_branch || true
      git checkout -b source_branch source/$SOURCE_BRANCH || {
        echo "Branch $SOURCE_BRANCH not exist on $SOURCE_REPO"
        EXIT_CODE=2
        continue
      }

      set +x
      echo

      for TARGET in $TARGET_ENDPOINTS
      do
        TARGET_REPO=`echo $TARGET | cut -d! -f 1 -`
        TARGET_BRANCH=`echo $TARGET | cut -d! -f 2 -`
        echo "TARGET_REPO=$TARGET_REPO"
        echo "TARGET_BRANCH=$TARGET_BRANCH"

        [[ $TARGET_BRANCH == $SOURCE_BRANCH ]] || {
          echo "Skip syncing branch $TARGET_BRANCH"
          continue;
        }

        set -x

        git checkout source_branch
        git reset --hard refs/remotes/source/$SOURCE_BRANCH
        git remote remove target 2> /dev/null || true
        git remote add target $TARGET_REPO

        git branch -D target_branch 2> /dev/null || true
        ( git fetch --no-tags target $TARGET_BRANCH && git checkout -b target_branch refs/remotes/target/$TARGET_BRANCH ) || {
          git checkout -b target_branch
        }
        git rebase --strategy-option=theirs refs/heads/source_branch || {
          echo "Failed to rebase!" >&2
          EXIT_CODE=2
          git status
          git diff
          git rebase --abort
          git reset --hard refs/remotes/target/$TARGET_BRANCH
        }
        git push -f target target_branch:refs/heads/$TARGET_BRANCH

        set +x
        echo
      done # for $TARGET_ENDPOINTS

    done # for $SOURCE_BRANCHES

    rm -rf *

    exit $EXIT_CODE
  workingDirectory: ${{ parameters.WORKING_DIRECTORY }}
  continueOnError: true
  displayName: Mirror ${{ parameters.SOURCE_REPO }} -- ${{ parameters.SOURCE_BRANCHES }}
  timeoutInMinutes: 10
